/**
 * Context Management Routes
 */

import { Router, Request, Response } from 'express';
import { getContextEngine, getLLMContextAnalyst, getContextRepository, getObservationRepository } from '../services/service-container';
import { getUserId } from '../utils/identity';

import { getErrorMessage } from '../utils/error';
import { ObservationSource, ObservationType, type Observation, type ContextCorrection, type ContextAnalystRequest } from '../domain/types';

export const contextRouter = Router();

// Get current context
contextRouter.get('/', async (req: Request, res: Response) => {
  try {
    const userId = getUserId(req);
    const contextEngine = getContextEngine();

    const context = await contextEngine.getCurrentContext(userId);

    res.json(context);
  } catch (error: unknown) {
    res.status(500).json({ error: getErrorMessage(error) });
  }
});

// Setup context
contextRouter.post('/setup', async (req: Request, res: Response) => {
  try {
    const body: unknown = req.body;
    let answers: { questionId: string, text: string }[] = [];

    if (body === null || typeof body !== 'object' || Array.isArray(body)) {
      return res.status(400).json({ error: 'request body must be an object' });
    }

    const setupBody = body as { answers?: unknown };
    if (Array.isArray(setupBody.answers)) {
      for (const ans of setupBody.answers) {
        if (!ans || typeof ans !== 'object') {
          return res.status(400).json({ error: 'invalid answer item' });
        }
        const answerObj = ans as { questionId?: unknown; text?: unknown };
        if (typeof answerObj.questionId !== 'string' || typeof answerObj.text !== 'string') {
          return res.status(400).json({ error: 'questionId and text must be strings' });
        }
      }
      answers = setupBody.answers as { questionId: string, text: string }[];
    } else if (setupBody.answers !== undefined) {
      return res.status(400).json({ error: 'answers must be an array' });
    }

    const userId = getUserId(req);

    if (answers.length > 4) {
      return res.status(400).json({ error: 'Maximum 4 answers allowed' });
    }

    const contextEngine = getContextEngine();
    const contextRepo = getContextRepository();

    for (const answer of answers) {
      await contextEngine.updateContext(userId, {
        id: '', // will be generated by repo
        userId,
        type: ObservationType.USER_REPORTED,
        data: { questionId: answer.questionId, text: answer.text },
        source: ObservationSource.USER_CONFIRMED,
        confidence: 1.0,
        timestamp: new Date(),
        createdAt: new Date()
      });

      await contextRepo.create({
        userId,
        attribute: 'onboarding_answer',
        value: JSON.stringify({ questionId: answer.questionId, text: answer.text }),
        source: ObservationSource.USER_CONFIRMED,
        confidence: 1.0,
        observedAt: new Date()
      });
    }

    // Set setup completed marker
    await contextRepo.create({
      userId,
      attribute: 'setup_completed',
      value: JSON.stringify(true),
      source: ObservationSource.USER_CONFIRMED,
      confidence: 1.0,
      observedAt: new Date()
    });

    res.json({ setupCompleted: true });
  } catch (error: unknown) {
    res.status(500).json({ error: getErrorMessage(error) });
  }
});

// Update context (manual or observation)
contextRouter.post('/update', async (req: Request, res: Response) => {
  try {
    const body = req.body as { observation?: Observation };
    const userId = getUserId(req);
    const observation = body.observation;

    if (!observation) {
      return res.status(400).json({ error: 'Observation is required' });
    }

    const contextEngine = getContextEngine();
    const context = await contextEngine.updateContext(userId, observation);

    res.json(context);
  } catch (error: unknown) {
    res.status(500).json({ error: getErrorMessage(error) });
  }
});

// Confirm inferred attribute
contextRouter.post('/confirm', async (req: Request, res: Response) => {
  try {
    const body = req.body as { attributeId?: string };
    const userId = getUserId(req);
    const attributeId = body.attributeId;

    if (!attributeId) {
      return res.status(400).json({ error: 'attributeId is required' });
    }

    const contextRepo = getContextRepository();
    const attr = await contextRepo.findById(attributeId);
    if (!attr) return res.status(404).json({ error: 'Attribute not found' });
    if (attr.userId !== userId) return res.status(403).json({ error: 'Forbidden' });

    const contextEngine = getContextEngine();
    await contextEngine.confirmContextAttribute(userId, attributeId);

    res.json({ success: true });
  } catch (error: unknown) {
    res.status(500).json({ error: getErrorMessage(error) });
  }
});

// Correct wrong context
contextRouter.post('/correct', async (req: Request, res: Response) => {
  try {
    const body = req.body as { correction?: ContextCorrection };
    const userId = getUserId(req);
    const correction = body.correction;

    if (!correction || typeof correction.attributeId !== 'string' || typeof correction.correctedValue !== 'string') {
      return res.status(400).json({ error: 'Valid correction object is required' });
    }

    const contextRepo = getContextRepository();
    const attr = await contextRepo.findById(correction.attributeId);
    if (!attr) return res.status(404).json({ error: 'Attribute not found' });
    if (attr.userId !== userId) return res.status(403).json({ error: 'Forbidden' });

    const contextEngine = getContextEngine();
    const context = await contextEngine.correctContext(userId, correction);

    res.json(context);
  } catch (error: unknown) {
    res.status(500).json({ error: getErrorMessage(error) });
  }
});

// Analyze context for uncertainty and hypotheses
contextRouter.post('/analyze', async (req: Request, res: Response) => {
  try {
    const userId = getUserId(req);
    const contextRepo = getContextRepository();
    const observationRepo = getObservationRepository();
    const llmAnalyst = getLLMContextAnalyst();

    const allContext = await contextRepo.findByUserId(userId);
    const uncertainAttributes = allContext
      .filter(attr => attr.source !== ObservationSource.USER_CONFIRMED && attr.confidence < 1.0)
      .sort((a, b) => b.observedAt.getTime() - a.observedAt.getTime())
      .slice(0, 10);

    // Get recent observations (last 24h)
    const twentyFourHoursAgo = new Date(Date.now() - 24 * 60 * 60 * 1000);
    const allObservations = await observationRepo.findByUserId(userId);
    const recentObservations = allObservations
      .filter(obs => obs.timestamp >= twentyFourHoursAgo)
      .sort((a, b) => b.timestamp.getTime() - a.timestamp.getTime())
      .slice(0, 20);

    // Build ContextAnalystRequest
    const analystRequest: ContextAnalystRequest = {
      signals: recentObservations.map(obs => ({
        id: obs.id,
        description: `${obs.type}: ${JSON.stringify(obs.data)}`,
        evidenceIds: [obs.id]
      })),
      evidence: recentObservations.map(obs => ({
        id: obs.id,
        description: `${obs.type}: ${JSON.stringify(obs.data)}`
      })),
      contextAttributes: uncertainAttributes.map(attr => ({
        id: attr.id,
        value: typeof attr.value === 'string' ? attr.value : JSON.stringify(attr.value)
      }))
    };

    if (analystRequest.signals.length === 0 || analystRequest.contextAttributes.length === 0) {
      console.log('Skipping analyze. Signals:', analystRequest.signals.length, 'Attributes:', analystRequest.contextAttributes.length);
      return res.status(200).json({
        proposedHypotheses: [],
        candidateClarificationQuestions: [],
        validation: { status: 'accepted' },
        skipped: true,
        reason: 'no-signals-or-attributes'
      });
    }

    const result = await llmAnalyst.analyze(analystRequest);
    return res.status(200).json(result);
  } catch (error: unknown) {
    // If the analyst throws unexpectedly, we return 200 with rejected validation per specs
    return res.status(200).json({
      proposedHypotheses: [],
      candidateClarificationQuestions: [],
      validation: { status: 'rejected', reason: 'invalid-request', errors: [getErrorMessage(error)] }
    });
  }
});

// Get context understanding evolution history (time-windowed counts)
contextRouter.get('/history', async (req: Request, res: Response) => {
  try {
    const userId = getUserId(req);
    const contextRepo = getContextRepository();

    const rawDays = typeof req.query.days === 'string' ? parseInt(req.query.days, 10) : 30;
    const days = Math.max(1, Math.min(90, Number.isFinite(rawDays) ? rawDays : 30));

    const attributes = await contextRepo.findByUserId(userId, 500);
    const now = new Date();

    // Skip system/meta attributes; only count persona data
    const SKIP_ATTRS = new Set(['setup_completed', 'calendar_last_sync', 'calendar-sync', 'onboarding_answer', 'setup', 'expired']);
    const relevant = attributes.filter(a => !SKIP_ATTRS.has(a.attribute) && !a.attribute.startsWith('calendar'));

    // Build 7 equally-spaced data points from (now - days) to now
    const POINTS = 7;
    const history = Array.from({ length: POINTS }, (_, i) => {
      // i=0 is oldest, i=6 is now
      const fraction = i / (POINTS - 1);
      const t = new Date(now.getTime() - (1 - fraction) * days * 86_400_000);
      const label = i === POINTS - 1 ? 'Today' : `-${Math.round((1 - fraction) * days)}d`;

      let goals = 0;
      let commitments = 0;
      let preferences = 0;
      let decisions = 0;

      for (const attr of relevant) {
        const observedAt = attr.observedAt instanceof Date ? attr.observedAt : new Date(attr.observedAt);
        const validUntil = attr.validUntil ? (attr.validUntil instanceof Date ? attr.validUntil : new Date(attr.validUntil)) : null;
        if (observedAt > t) continue;
        if (validUntil && validUntil <= t) continue;
        if (attr.attribute.startsWith('goal:')) goals++;
        else if (attr.attribute.startsWith('commitment:')) commitments++;
        else if (attr.attribute.startsWith('preference:')) preferences++;
        else if (attr.attribute.startsWith('decision:')) decisions++;
      }

      return { label, goals, commitments, preferences, decisions };
    });

    res.json({ history });
  } catch (error: unknown) {
    res.status(500).json({ error: getErrorMessage(error) });
  }
});

// Clarify an uncertain context attribute
contextRouter.post('/clarify', async (req: Request, res: Response) => {
  try {
    const body = req.body as { attributeId?: string; answer?: string; questionText?: string };
    const userId = getUserId(req);
    const attributeId = body.attributeId;
    const answer = body.answer;
    const questionText = body.questionText;

    if (!attributeId || typeof attributeId !== 'string') {
      return res.status(400).json({ error: 'attributeId is required and must be a string' });
    }
    if (!answer || typeof answer !== 'string') {
      return res.status(400).json({ error: 'answer is required and must be a string' });
    }
    if (answer.length > 500) {
      return res.status(400).json({ error: 'answer must be at most 500 characters' });
    }

    const contextRepo = getContextRepository();
    const existingAttr = await contextRepo.findById(attributeId);

    if (!existingAttr) {
      return res.status(404).json({ error: 'Attribute not found' });
    }
    if (existingAttr.userId !== userId) {
      return res.status(403).json({ error: 'Forbidden' });
    }

    const contextEngine = getContextEngine();
    const correction: ContextCorrection = {
      attributeId,
      correctedValue: answer.trim(),
      reason: questionText || 'User clarification via prompt'
    };

    const updatedContext = await contextEngine.correctContext(userId, correction);
    return res.json(updatedContext);
  } catch (error: unknown) {
    return res.status(500).json({ error: getErrorMessage(error) });
  }
});
