import { useState } from 'react';
import { selectCapacitySummary, selectHistoryAndLearnedSignal, useDemoWorld, type Goal } from '../demo-world';

function capacityDays(world: ReturnType<typeof useDemoWorld>['world']) {
 const start = new Date(`${world.period.start}T00:00:00Z`); const end = new Date(`${world.period.end}T00:00:00Z`); const days=[];
 for(let date=start;date<=end;date=new Date(date.getTime()+86_400_000)){ const iso=date.toISOString().slice(0,10); const events=world.calendarEvents.filter(event=>event.start.slice(0,10)===iso); const minutes=events.reduce((total,event)=>total+(new Date(`${event.end}:00Z`).getTime()-new Date(`${event.start}:00Z`).getTime())/60_000,0); days.push({iso,label:new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',timeZone:'UTC'}).format(date),load:Math.max(8,Math.min(100,Math.round(minutes/5.4))),relocated:events.some(event=>event.id==='event.weekly-planning.2026-10-13'),focused:events.some(event=>event.id==='event.focused-mentoring.2026-10-16')}); }
 return days;
}
const Badge=({children,tone='slate'}:{children:React.ReactNode;tone?:'slate'|'blue'|'violet'|'green'})=><span className={`inline-flex rounded-full px-2.5 py-1 text-[11px] font-bold ${tone==='blue'?'bg-blue-50 text-blue-700':tone==='violet'?'bg-violet-50 text-violet-700':tone==='green'?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-600'}`}>{children}</span>;
function GoalEditor({goal,onSave}:{goal:Goal;onSave:(title:string)=>void}){ const [editing,setEditing]=useState(false); const [title,setTitle]=useState(goal.title); return <div className="rounded-xl border border-violet-100 bg-violet-50 p-3 font-semibold">{editing?<><input aria-label={`Edit ${goal.title}`} className="w-full rounded-lg border border-violet-200 bg-white px-3 py-2 text-sm" value={title} onChange={e=>setTitle(e.target.value)}/><button onClick={()=>{if(title.trim())onSave(title.trim());setEditing(false)}} className="mt-2 text-xs font-bold text-primary">Save</button></>:<>{goal.title}<div className="mt-2 flex items-center gap-2"><Badge>User Reported · Editable</Badge><button onClick={()=>setEditing(true)} className="text-xs font-bold text-primary">Update</button></div></>}</div>; }

export function ContextPage(){
 const {world,dispatch,resetVersion}=useDemoWorld(); const capacity=selectCapacitySummary(world); const history=selectHistoryAndLearnedSignal(world); const days=capacityDays(world); const activeOpportunity=world.activeDecision ? world.opportunities.find(o=>o.id==='opportunity.student-startup-mentoring') : undefined; const workshop=world.opportunities.find(o=>o.id==='opportunity.professional-workshop'); const expected=world.activeDecision?.clarifications.find(c=>c.id==='expected-outcome')?.answer;
 return <main className="mx-auto max-w-[1400px] space-y-7 px-5 py-8 lg:px-10"><header><p className="text-xs font-bold uppercase tracking-[.2em] text-primary">Persona A · living context model</p><h1 className="mt-2 text-4xl text-text-primary">What Future Me Understands</h1><p className="mt-2 max-w-3xl text-text-secondary">What is known, where it came from, what you can correct, and how it shapes decisions.</p></header>
 <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
  <article className="card p-5"><h2 className="text-xl text-text-primary">Capacity</h2><p className="mt-3 font-semibold">High workload · {capacity.availableCapacity === 'limited' ? 'Limited' : 'Restructured'} usable capacity</p><p className="mt-1 text-sm text-text-secondary">{capacity.focusCapacity}</p><div className="mt-3"><Badge tone="violet">Derived</Badge></div></article>
  <article className="card p-5"><h2 className="text-xl text-text-primary">Commitments</h2><p className="mt-3 font-semibold">{world.calendarEvents.filter(e=>e.kind==='fixed').length} fixed anchors</p><p className="mt-1 text-sm text-text-secondary">1 hard deadline · flexible work can be adjusted safely</p><div className="mt-3"><Badge tone="blue">Imported / Source Data</Badge></div></article>
  <article className="card p-5"><h2 className="text-xl text-text-primary">Personal Direction</h2><p className="mt-3 font-semibold">Venture growth + mentoring</p><p className="mt-1 text-sm text-text-secondary">Protect deadlines, teaching, and sustainable balance</p><div className="mt-3"><Badge>User Reported</Badge></div></article>
  <article className="card p-5"><h2 className="text-xl text-text-primary">History & Reflection</h2><p className="mt-3 font-semibold">Bounded commitments fit better</p><p className="mt-1 text-sm text-text-secondary">{history.learnedSignals.length ? 'Preparation buffer updated from outcome' : 'No future outcome claimed yet'}</p><div className="mt-3"><Badge tone="green">Observed History</Badge></div></article>
 </section>

 {activeOpportunity&&<section className="rounded-3xl border border-violet-200 bg-violet-50 p-6"><h2 className="text-2xl text-text-primary">Current Opportunity / Expected Value</h2><div className="mt-4 grid gap-3 md:grid-cols-3"><div className="rounded-xl bg-white p-4"><p className="text-xs font-bold uppercase text-text-secondary">Expected Outcome</p><p className="mt-2 font-semibold">{expected ?? 'Unknown / needs clarification'}</p><Badge>User Reported</Badge></div><div className="rounded-xl bg-white p-4"><p className="text-xs font-bold uppercase text-text-secondary">Opportunity Value</p><p className="mt-2 font-semibold capitalize">{activeOpportunity.value.level} alignment</p><div className="mt-2 flex items-center gap-2"><Badge tone="violet">{activeOpportunity.value.overridden?'User Reported':'Inferred · Correctable'}</Badge><button aria-label="Correct mentoring opportunity value" onClick={()=>dispatch({type:'override-opportunity-value',opportunityId:activeOpportunity.id,value:'moderate'})} className="text-xs font-bold text-primary">Correct</button></div></div><div className="rounded-xl bg-white p-4"><p className="text-xs font-bold uppercase text-text-secondary">Required Commitment</p><p className="mt-2 font-semibold">{activeOpportunity.requiredCommitment}</p><Badge tone="blue">Imported / Source Data</Badge></div></div></section>}

 <section className="grid gap-6 lg:grid-cols-[1.2fr_.8fr]">
  <article className="card p-6"><div className="flex items-end justify-between"><div><p className="text-xs font-bold uppercase text-primary">Capacity</p><h2 className="mt-1 text-2xl text-text-primary">14-day Capacity Timeline</h2></div><Badge tone="violet">Derived · read-only</Badge></div><div className="mt-6 flex h-56 items-end gap-2" aria-label="14-day capacity chart">{days.map(day=><div key={day.iso} className="flex h-full min-w-0 flex-1 flex-col justify-end"><span className="mb-1 min-h-8 text-center text-[9px] font-semibold text-violet-700">{day.relocated?'Weekly Planning relocated':day.focused?'Focused mentoring plan':''}</span><div className={`rounded-t-md ${day.load>85?'bg-red-400':day.load<25?'bg-emerald-300':day.load<55?'bg-violet-400':'bg-amber-400'}`} style={{height:`${day.load}%`}} title={`${day.label}: ${day.load}% committed load`}/><span className="mt-2 -rotate-45 whitespace-nowrap text-[10px] text-text-secondary">{day.label}</span></div>)}</div><div className="mt-8 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-bold uppercase">Time Available</p><p className="mt-1 font-semibold">Fixed two-week view</p><Badge tone="violet">Derived</Badge></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-bold uppercase">Workload</p><p className="mt-1 font-semibold capitalize">{capacity.workload}</p><Badge tone="violet">Derived</Badge></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-bold uppercase">Focus Capacity</p><p className="mt-1 font-semibold">{capacity.focusCapacity}</p><Badge tone="green">Observed History</Badge></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-bold uppercase">Mental Well-being</p><p className="mt-1 font-semibold">{world.capacityProfile.mentalWellbeing.value==='slightly-strained'?'Slightly strained':'Steady'}</p><div className="mt-2 flex items-center gap-2"><Badge>User Reported</Badge><button aria-label="Update mental well-being" onClick={()=>dispatch({type:'update-mental-wellbeing',value:'steady'})} className="text-xs font-bold text-primary">Update</button></div></div></div></article>
  <article className="card p-6"><p className="text-xs font-bold uppercase text-primary">Commitments</p><h2 className="mt-1 text-2xl text-text-primary">Protected, fixed, flexible</h2><div className="mt-4 space-y-3">{[['Future Calendar','Fixed teaching, meetings, protected weekends'],['Tasks',`${world.tasks.length} shared tasks and deadline records`],['Deadlines','Client Proposal · Oct 8, 19:00'],['Commitment Flexibility','Monthly Report and Weekly Planning are flexible']].map(([label,text])=><div key={label} className="rounded-xl border border-surface-border p-3"><p className="text-xs font-bold uppercase text-text-secondary">{label}</p><p className="mt-1 text-sm font-semibold">{text}</p><Badge tone="blue">Imported / Source Data</Badge></div>)}</div></article>
 </section>

 <article className="card p-6"><p className="text-xs font-bold uppercase text-primary">Personal Direction</p><h2 className="mt-1 text-2xl text-text-primary">Goals connected across time horizons</h2><div className="mt-6 grid gap-6 lg:grid-cols-[1fr_auto_1fr]"><div><p className="text-xs font-black tracking-[.2em] text-violet-700">LONG TERM</p><div className="mt-3 space-y-2">{world.goals.filter(g=>g.horizon==='long-term').map(g=><GoalEditor key={`${g.id}:${g.title}:${resetVersion}`} goal={g} onSave={title=>dispatch({type:'update-goal',goalId:g.id,title})}/>)}</div></div><div className="hidden place-items-center text-3xl text-violet-300 lg:grid">↔</div><div><p className="text-xs font-black tracking-[.2em] text-amber-700">SHORT TERM</p><div className="mt-3 space-y-2">{world.goals.filter(g=>g.horizon==='short-term').map(g=><GoalEditor key={`${g.id}:${g.title}:${resetVersion}`} goal={g} onSave={title=>dispatch({type:'update-goal',goalId:g.id,title})}/>)}</div></div></div><p className="mt-5 rounded-xl bg-slate-50 p-4 text-sm text-text-secondary">Mentoring aligns with long-term startup and advisory direction, while a bounded format protects short-term teaching, deadlines, and recovery.</p></article>

 <section className="grid gap-6 lg:grid-cols-2"><article className="card p-6"><p className="text-xs font-bold uppercase text-primary">Correctable understanding</p><h2 className="mt-1 text-2xl">Opportunity value</h2><p className="mt-3 font-semibold">Workshop value: {workshop?.value.level}</p><Badge tone="violet">{workshop?.value.provenance==='inferred'?'Inferred':'User Reported'}</Badge><button aria-label="Correct workshop value" onClick={()=>dispatch({type:'override-opportunity-value',opportunityId:'opportunity.professional-workshop',value:'low'})} className="ml-3 text-sm font-bold text-primary">Correct</button>{workshop?.value.overridden&&<p className="mt-3 text-sm font-semibold text-emerald-700">Workshop value corrected to Low.</p>}</article><article className="card p-6"><p className="text-xs font-bold uppercase text-primary">History & Reflection</p><h2 className="mt-1 text-2xl">What outcomes changed</h2><div className="mt-4 rounded-xl bg-violet-50 p-4"><p className="font-semibold">{world.historicalPreferences[0]?.text}</p><div className="mt-2 flex items-center gap-2"><Badge tone="violet">{world.historicalPreferences[0]?.corrected?'Observed History':'Inferred · Correctable'}</Badge><button aria-label="Correct historical preference" onClick={()=>dispatch({type:'correct-historical-preference',preferenceId:'preference.bounded-advisory',text:'Prefer clearly bounded advisory formats with explicit preparation time.'})} className="text-xs font-bold text-primary">Correct</button></div></div>{history.outcomes.map(o=><div key={o.id} className="mt-3 rounded-xl bg-emerald-50 p-4"><p className="font-semibold">Estimated preparation: {o.estimatedPreparationMinutes.min}–{o.estimatedPreparationMinutes.max} min</p><p className="mt-1 font-semibold">Actual preparation: {o.actualPreparationMinutes} min</p><Badge tone="green">Observed History</Badge></div>)}{history.learnedSignals.map(s=><p key={s.id} className="mt-3 rounded-xl border border-violet-200 p-4 font-semibold text-violet-950">{s.text}</p>)}</article></section>
 </main>;
}
export default ContextPage;
