import '@testing-library/jest-dom/vitest';
import { beforeEach, describe, expect, it } from 'vitest';
import { fireEvent, render, screen } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import { DemoWorldProvider, useDemoWorld } from '../demo-world';
import ContextPage from './ContextPage';

function ActiveOpportunity() { const {dispatch}=useDemoWorld(); return <button onClick={()=>dispatch({type:'start-mentoring-decision'})}>Activate opportunity</button>; }
function CompleteMentoring() { const {dispatch}=useDemoWorld(); const run=()=>{dispatch({type:'start-mentoring-decision'});dispatch({type:'answer-expected-outcome',answer:'meaningful-limited'});dispatch({type:'answer-commitment-flexibility',answer:'scope-and-schedule-adjustable'});dispatch({type:'use-mentoring-plan'});dispatch({type:'set-team-availability',availability:'flexible-best-fit'});dispatch({type:'apply-active-plan'});dispatch({type:'complete-mentoring-with-reflection',actualPreparationMinutes:75});}; return <button onClick={run}>Complete fixture</button>; }
function ApplyPlan() { const {dispatch}=useDemoWorld(); const run=()=>{dispatch({type:'start-mentoring-decision'});dispatch({type:'answer-expected-outcome',answer:'meaningful-limited'});dispatch({type:'answer-commitment-flexibility',answer:'scope-and-schedule-adjustable'});dispatch({type:'use-mentoring-plan'});dispatch({type:'set-team-availability',availability:'flexible-best-fit'});dispatch({type:'apply-active-plan'});}; return <button onClick={run}>Apply fixture</button>; }
function CorrectPreparation() { const {dispatch}=useDemoWorld(); return <button onClick={()=>dispatch({type:'correct-mentoring-preparation',actualPreparationMinutes:40})}>Correct preparation fixture</button>; }
function ResetControl() { const {resetDemo}=useDemoWorld(); return <button onClick={resetDemo}>Reset fixture</button>; }
const renderPage=(extra?:React.ReactNode)=>render(<DemoWorldProvider><MemoryRouter>{extra}<ContextPage/></MemoryRouter></DemoWorldProvider>);

describe('ContextPage pitch understanding',()=>{
 beforeEach(()=>localStorage.clear());
 it('shows four summaries, all capacity attributes, a fixed 14-day capacity view, provenance, and structured direction',()=>{renderPage(); ['Capacity','Commitments','Personal Direction','History & Reflection'].forEach(title=>expect(screen.getByRole('heading',{name:title})).toBeInTheDocument()); expect(screen.getByText('14-day Capacity Timeline')).toBeInTheDocument(); expect(screen.getByText('Time Available')).toBeInTheDocument(); expect(screen.getByText('Focus Capacity')).toBeInTheDocument(); expect(screen.getByText('Mental Well-being')).toBeInTheDocument(); expect(screen.getAllByText('User Reported').length).toBeGreaterThan(0); expect(screen.getAllByText('Imported / Source Data').length).toBeGreaterThan(0); expect(screen.getAllByText('Derived').length).toBeGreaterThan(0); expect(screen.getByText('LONG TERM')).toBeInTheDocument(); expect(screen.getByText('SHORT TERM')).toBeInTheDocument();});
 it('allows user-owned updates and inferred corrections but not direct derived editing',()=>{renderPage(); fireEvent.click(screen.getByRole('button',{name:'Update mental well-being'})); expect(screen.getByText('Steady')).toBeInTheDocument(); fireEvent.click(screen.getAllByRole('button',{name:'Update'})[0]!); const goal=screen.getByRole('textbox',{name:/Edit Grow a sustainable technology venture/i}); fireEvent.change(goal,{target:{value:'Grow a resilient technology venture'}}); fireEvent.click(screen.getByRole('button',{name:'Save'})); expect(screen.getByText('Grow a resilient technology venture')).toBeInTheDocument(); fireEvent.click(screen.getByRole('button',{name:'Correct workshop value'})); expect(screen.getByText(/Workshop value corrected to Low/i)).toBeInTheDocument(); fireEvent.click(screen.getByRole('button',{name:'Correct historical preference'})); expect(screen.getByText(/explicit preparation time/i)).toBeInTheDocument(); expect(screen.queryByRole('button',{name:/Edit available capacity/i})).not.toBeInTheDocument();});
 it('shows and corrects the active opportunity, then adds learning only after completion',()=>{renderPage(<><ActiveOpportunity/><CompleteMentoring/></>); fireEvent.click(screen.getByRole('button',{name:'Activate opportunity'})); expect(screen.getByRole('heading',{name:'Current Opportunity / Expected Value'})).toBeInTheDocument(); expect(screen.getByText('Unknown / needs clarification')).toBeInTheDocument(); fireEvent.click(screen.getByRole('button',{name:'Correct mentoring opportunity value'})); expect(screen.getByText('moderate alignment')).toBeInTheDocument(); expect(screen.queryByText(/more preparation than previously expected/i)).not.toBeInTheDocument(); fireEvent.click(screen.getByRole('button',{name:'Complete fixture'})); expect(screen.getByText(/more preparation than previously expected/i)).toBeInTheDocument(); expect(screen.getByText('Actual preparation: 75 min')).toBeInTheDocument();});
 it('derives the timeline from shared calendar changes before and after applying the plan',()=>{renderPage(<ApplyPlan/>); expect(screen.queryByText('Weekly Planning relocated')).not.toBeInTheDocument(); expect(screen.queryByText('Focused mentoring plan')).not.toBeInTheDocument(); fireEvent.click(screen.getByRole('button',{name:'Apply fixture'})); expect(screen.getByText('Weekly Planning relocated')).toBeInTheDocument(); expect(screen.getByText('Focused mentoring plan')).toBeInTheDocument();});
 it('renders corrected preparation and learning from the shared outcome',()=>{renderPage(<><CompleteMentoring/><CorrectPreparation/></>); fireEvent.click(screen.getByRole('button',{name:'Complete fixture'})); fireEvent.click(screen.getByRole('button',{name:'Correct preparation fixture'})); expect(screen.getByText('Actual preparation: 40 min')).toBeInTheDocument(); expect(screen.getByText(/stayed within the estimated 30–45 minute preparation range/i)).toBeInTheDocument(); expect(screen.queryByText(/more preparation than previously expected/i)).not.toBeInTheDocument();});
 it('clears a mounted goal editor draft and edit mode when the demo resets',()=>{renderPage(<ResetControl/>); fireEvent.click(screen.getAllByRole('button',{name:'Update'})[0]!); const goal=screen.getByRole('textbox',{name:/Edit Grow a sustainable technology venture/i}); fireEvent.change(goal,{target:{value:'Unsaved goal draft'}}); fireEvent.click(screen.getByRole('button',{name:'Reset fixture'})); expect(screen.queryByRole('textbox',{name:/Edit/i})).not.toBeInTheDocument(); expect(screen.getByText('Grow a sustainable technology venture')).toBeInTheDocument(); expect(screen.queryByDisplayValue('Unsaved goal draft')).not.toBeInTheDocument();});
});
