import '@testing-library/jest-dom/vitest';
import { beforeEach, describe, expect, it } from 'vitest';
import { fireEvent, render, screen } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import { DemoWorldProvider, useDemoWorld } from '../demo-world';
import HistoryPage from './HistoryPage';

function Controls() { const { dispatch } = useDemoWorld(); const apply=()=>{dispatch({type:'start-mentoring-decision'});dispatch({type:'answer-expected-outcome',answer:'meaningful-limited'});dispatch({type:'answer-commitment-flexibility',answer:'scope-and-schedule-adjustable'});dispatch({type:'use-mentoring-plan'});dispatch({type:'set-team-availability',availability:'flexible-best-fit'});dispatch({type:'apply-active-plan'});}; return <><button onClick={apply}>Apply fixture</button><button onClick={()=>dispatch({type:'complete-mentoring-with-reflection',actualPreparationMinutes:75})}>Complete fixture</button></>; }

describe('HistoryPage', () => { beforeEach(()=>localStorage.clear()); it('keeps planned decision separate from actual outcome and then shows learned reflection',()=>{render(<DemoWorldProvider><MemoryRouter><Controls/><HistoryPage/></MemoryRouter></DemoWorldProvider>); expect(screen.queryByText('Actual preparation: 75 min')).not.toBeInTheDocument(); fireEvent.click(screen.getByRole('button',{name:'Apply fixture'})); expect(screen.getByText('Planned')).toBeInTheDocument(); expect(screen.queryByText('Actual preparation: 75 min')).not.toBeInTheDocument(); fireEvent.click(screen.getByRole('button',{name:'Complete fixture'})); expect(screen.getByText('Estimated preparation: 30–45 min')).toBeInTheDocument(); expect(screen.getByText('Actual preparation: 75 min')).toBeInTheDocument(); expect(screen.getByText(/more preparation than previously expected/i)).toBeInTheDocument();}); it('propagates a non-75 correction through outcome, decision, and learning',()=>{render(<DemoWorldProvider><MemoryRouter><Controls/><HistoryPage/></MemoryRouter></DemoWorldProvider>); fireEvent.click(screen.getByRole('button',{name:'Apply fixture'})); fireEvent.click(screen.getByRole('button',{name:'Complete fixture'})); fireEvent.click(screen.getByRole('button',{name:'Correct actual preparation time'})); fireEvent.change(screen.getByLabelText('Actual preparation minutes'),{target:{value:'40'}}); fireEvent.click(screen.getByRole('button',{name:'Save'})); expect(screen.getByText('Actual preparation: 40 min')).toBeInTheDocument(); expect(screen.getByText(/Actual outcome:.*preparation corrected to 40 minutes/i)).toBeInTheDocument(); expect(screen.getByText(/stayed within the estimated 30–45 minute preparation range/i)).toBeInTheDocument(); expect(screen.queryByText(/more preparation than previously expected/i)).not.toBeInTheDocument();});});
